name: Build, test, check!

on:
  push:
jobs:

  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [exe1, exe2, exe3, exe4, exe5]
    steps:
      - uses: actions/checkout@v5
      - uses: insper-embarcados/pico-build@v1
      - uses: insper-embarcados/actions-wokwi-test@v3
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          test_name: ${{ matrix.test }}
      - uses: insper-embarcados/actions-firmware-rubric-check@v0
        with:
          c_file: ${{ matrix.test }}/main.c
          rubric_file: ${{ matrix.test }}/rubric_firmware.yml
      - uses: insper-embarcados/actions-embedded-check@v1
        with:
          c_file: ${{ matrix.test }}/main.c
      - uses: insper-embarcados/actions-cppcheck@v1
        with:
          c_file: ${{ matrix.test }}/main.c

